Combined PR of KaleoFormsProcessSubmissionsDetails testcases: LRQA-70700, LRQA-70701, LRQA-70702, LRQA-70703, LRQA-70704
lucasperj/liferay-portal pull request #107
Opened 2021-10-25 21:18 UTC by alanafergs

https://issues.liferay.com/browse/LRQA-70703

2021-11-24 20:10 UTC, lucasperj commented
ci:test:sf

2021-11-24 20:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/793/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/793/jenkins-report.html">here</a>.</b></p>

2021-11-24 20:13 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4298ad99f775c4f55fe518b02ec20222be4558c6">4298ad99f775c4f55fe518b02ec20222be4558c6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/9038b8aaee7919f7c75bba33bd1dd93f840b0120">9038b8aaee7919f7c75bba33bd1dd93f840b0120</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/793/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/793/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/tests/packages/com.liferay.poshi.runner.html expected:&lt;&lt;!DOCTYPE html&gt;
     [java] [
     [java] &lt;html&gt;
     [java] &lt;head&gt;
     [java] &lt;meta content="text/html; charset=utf-8" http-equiv="Content-Type" /&gt;
     [java] &lt;meta content="IE=edge" http-equiv="x-ua-compatible" /&gt;
     [java] &lt;title&gt;Test results - Package com.liferay.poshi.runner&lt;/title&gt;
     [java] &lt;link href="../css/base-style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;link href="../css/style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;script src="../js/report.js" type="text/javascript"&gt;&lt;/script&gt;
     [java] &lt;/head&gt;
     [java] 
     [java] &lt;body&gt;
     [java] &lt;div id="content"&gt;
     [java] &lt;h1&gt;Package com.liferay.poshi.runner&lt;/h1&gt;
     [java] &lt;div class="breadcrumbs"&gt;
     [java] &lt;a href="../index.html"&gt;all&lt;/a&gt; &amp;gt; com.liferay.poshi.runner&lt;/div&gt;
     [java] &lt;div id="summary"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="summaryGroup"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="tests"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;tests&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="failures"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;failures&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="ignored"&gt;
     [java] &lt;div class="counter"&gt;0&lt;/div&gt;
     [java] &lt;p&gt;ignored&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="duration"&gt;
     [java] &lt;div class="counter"&gt;56.335s&lt;/div&gt;
     [java] &lt;p&gt;duration&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox failures" id="successRate"&gt;
     [java] &lt;div class="percent"&gt;0%&lt;/div&gt;
     [java] &lt;p&gt;successful&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] 
     [java] &lt;div id="tabs"&gt;
     [java] &lt;ul class="tabLinks"&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab0"&gt;Failed tests&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab1"&gt;Classes&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;/ul&gt;
     [java] 
     [java] &lt;div class="tab" id="tab0"&gt;
     [java] &lt;h2&gt;Failed tests&lt;/h2&gt;
     [java] &lt;ul class="linkList"&gt;
     [java] &lt;li&gt;</code></pre></details></html>

2021-11-24 20:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/793/">test-portal-source-format#793</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/793/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1583290153">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-11-24[12:10:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/2761/">publish-testray-report#2761</a><br/></div></div>

2021-11-30 22:09 UTC, alanafergs commented
ci:test:sf

2021-11-30 22:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/1103/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1103/jenkins-report.html">here</a>.</b></p>

2021-11-30 22:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f4c2369db680926981b7616a89042b3ff410456c">f4c2369db680926981b7616a89042b3ff410456c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/39774a48ff40d14733246588010ca05cc4f4f7bd">39774a48ff40d14733246588010ca05cc4f4f7bd</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1103/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1103/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/tests/packages/com.liferay.poshi.runner.html expected:&lt;&lt;!DOCTYPE html&gt;
     [java] [
     [java] &lt;html&gt;
     [java] &lt;head&gt;
     [java] &lt;meta content="text/html; charset=utf-8" http-equiv="Content-Type" /&gt;
     [java] &lt;meta content="IE=edge" http-equiv="x-ua-compatible" /&gt;
     [java] &lt;title&gt;Test results - Package com.liferay.poshi.runner&lt;/title&gt;
     [java] &lt;link href="../css/base-style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;link href="../css/style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;script src="../js/report.js" type="text/javascript"&gt;&lt;/script&gt;
     [java] &lt;/head&gt;
     [java] 
     [java] &lt;body&gt;
     [java] &lt;div id="content"&gt;
     [java] &lt;h1&gt;Package com.liferay.poshi.runner&lt;/h1&gt;
     [java] &lt;div class="breadcrumbs"&gt;
     [java] &lt;a href="../index.html"&gt;all&lt;/a&gt; &amp;gt; com.liferay.poshi.runner&lt;/div&gt;
     [java] &lt;div id="summary"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="summaryGroup"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="tests"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;tests&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="failures"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;failures&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="ignored"&gt;
     [java] &lt;div class="counter"&gt;0&lt;/div&gt;
     [java] &lt;p&gt;ignored&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="duration"&gt;
     [java] &lt;div class="counter"&gt;56.335s&lt;/div&gt;
     [java] &lt;p&gt;duration&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox failures" id="successRate"&gt;
     [java] &lt;div class="percent"&gt;0%&lt;/div&gt;
     [java] &lt;p&gt;successful&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] 
     [java] &lt;div id="tabs"&gt;
     [java] &lt;ul class="tabLinks"&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab0"&gt;Failed tests&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab1"&gt;Classes&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;/ul&gt;
     [java] 
     [java] &lt;div class="tab" id="tab0"&gt;
     [java] &lt;h2&gt;Failed tests&lt;/h2&gt;
     [java] &lt;ul class="linkList"&gt;
     [java] &lt;li&gt;</code></pre></details></html>

2021-11-30 22:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1103/">test-portal-source-format#1103</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1103/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1585434827">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-11-30[14:09:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/3689/">publish-testray-report#3689</a><br/></div></div>

2021-12-01 16:31 UTC, lucasperj commented
ci:test:sf

2021-12-01 16:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/1120/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1120/jenkins-report.html">here</a>.</b></p>

2021-12-01 16:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c49165737a2ea25992172d10b00afc89263b56a1">c49165737a2ea25992172d10b00afc89263b56a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/39774a48ff40d14733246588010ca05cc4f4f7bd">39774a48ff40d14733246588010ca05cc4f4f7bd</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1120/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1120/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/tests/packages/com.liferay.poshi.runner.html expected:&lt;&lt;!DOCTYPE html&gt;
     [java] [
     [java] &lt;html&gt;
     [java] &lt;head&gt;
     [java] &lt;meta content="text/html; charset=utf-8" http-equiv="Content-Type" /&gt;
     [java] &lt;meta content="IE=edge" http-equiv="x-ua-compatible" /&gt;
     [java] &lt;title&gt;Test results - Package com.liferay.poshi.runner&lt;/title&gt;
     [java] &lt;link href="../css/base-style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;link href="../css/style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;script src="../js/report.js" type="text/javascript"&gt;&lt;/script&gt;
     [java] &lt;/head&gt;
     [java] 
     [java] &lt;body&gt;
     [java] &lt;div id="content"&gt;
     [java] &lt;h1&gt;Package com.liferay.poshi.runner&lt;/h1&gt;
     [java] &lt;div class="breadcrumbs"&gt;
     [java] &lt;a href="../index.html"&gt;all&lt;/a&gt; &amp;gt; com.liferay.poshi.runner&lt;/div&gt;
     [java] &lt;div id="summary"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="summaryGroup"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="tests"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;tests&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="failures"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;failures&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="ignored"&gt;
     [java] &lt;div class="counter"&gt;0&lt;/div&gt;
     [java] &lt;p&gt;ignored&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="duration"&gt;
     [java] &lt;div class="counter"&gt;56.335s&lt;/div&gt;
     [java] &lt;p&gt;duration&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox failures" id="successRate"&gt;
     [java] &lt;div class="percent"&gt;0%&lt;/div&gt;
     [java] &lt;p&gt;successful&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] 
     [java] &lt;div id="tabs"&gt;
     [java] &lt;ul class="tabLinks"&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab0"&gt;Failed tests&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab1"&gt;Classes&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;/ul&gt;
     [java] 
     [java] &lt;div class="tab" id="tab0"&gt;
     [java] &lt;h2&gt;Failed tests&lt;/h2&gt;
     [java] &lt;ul class="linkList"&gt;
     [java] &lt;li&gt;</code></pre></details></html>

2021-12-01 16:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1120/">test-portal-source-format#1120</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1120/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1585911751">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-12-01[08:32:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/3730/">publish-testray-report#3730</a><br/></div></div>

2021-12-01 16:57 UTC, lucasperj commented
ci:test:sf

2021-12-01 16:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/974/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/974/jenkins-report.html">here</a>.</b></p>

2021-12-01 17:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e1c8d5c6443c1dc0bec32794754e0d1d43edbe46">e1c8d5c6443c1dc0bec32794754e0d1d43edbe46</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/d6e65ebd8a3d96358292619ff1f81ab837dcb1a8">d6e65ebd8a3d96358292619ff1f81ab837dcb1a8</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/974/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/974/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/tests/index.html expected:&lt;&lt;!DOCTYPE html&gt;
     [java] [
     [java] &lt;html&gt;
     [java] &lt;head&gt;
     [java] &lt;meta content="text/html; charset=utf-8" http-equiv="Content-Type" /&gt;
     [java] &lt;meta content="IE=edge" http-equiv="x-ua-compatible" /&gt;
     [java] &lt;title&gt;Test results - Test Summary&lt;/title&gt;
     [java] &lt;link href="css/base-style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;link href="css/style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;script src="js/report.js" type="text/javascript"&gt;&lt;/script&gt;
     [java] &lt;/head&gt;
     [java] 
     [java] &lt;body&gt;
     [java] &lt;div id="content"&gt;
     [java] &lt;h1&gt;Test Summary&lt;/h1&gt;
     [java] &lt;div id="summary"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="summaryGroup"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="tests"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;tests&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="failures"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;failures&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="ignored"&gt;
     [java] &lt;div class="counter"&gt;0&lt;/div&gt;
     [java] &lt;p&gt;ignored&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="duration"&gt;
     [java] &lt;div class="counter"&gt;56.335s&lt;/div&gt;
     [java] &lt;p&gt;duration&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox failures" id="successRate"&gt;
     [java] &lt;div class="percent"&gt;0%&lt;/div&gt;
     [java] &lt;p&gt;successful&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] 
     [java] &lt;div id="tabs"&gt;
     [java] &lt;ul class="tabLinks"&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab0"&gt;Failed tests&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab1"&gt;Packages&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab2"&gt;Classes&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;/ul&gt;
     [java] 
     [java] &lt;div class="tab" id="tab0"&gt;
     [java] &lt;h2&gt;Failed tests&lt;/h2&gt;
     [java] &lt;ul class="linkList"&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="classes/com.liferay.poshi.runner.PoshiRunner.html"&gt;PoshiRunner&lt;/a&gt;.</code></pre></details></html>

2021-12-01 19:53 UTC, alanafergs commented
ci:test:sf

2021-12-01 19:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/1158/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1158/jenkins-report.html">here</a>.</b></p>

2021-12-01 19:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/215417a0057bdf4ed0bbe961b384ffa52ecf4e09">215417a0057bdf4ed0bbe961b384ffa52ecf4e09</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/4502943a46a76a9dbd98de8d9bdccbcdf2c43205">4502943a46a76a9dbd98de8d9bdccbcdf2c43205</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1158/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1158/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/tests/packages/com.liferay.poshi.runner.html expected:&lt;&lt;!DOCTYPE html&gt;
     [java] [
     [java] &lt;html&gt;
     [java] &lt;head&gt;
     [java] &lt;meta content="text/html; charset=utf-8" http-equiv="Content-Type" /&gt;
     [java] &lt;meta content="IE=edge" http-equiv="x-ua-compatible" /&gt;
     [java] &lt;title&gt;Test results - Package com.liferay.poshi.runner&lt;/title&gt;
     [java] &lt;link href="../css/base-style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;link href="../css/style.css" rel="stylesheet" type="text/css" /&gt;
     [java] &lt;script src="../js/report.js" type="text/javascript"&gt;&lt;/script&gt;
     [java] &lt;/head&gt;
     [java] 
     [java] &lt;body&gt;
     [java] &lt;div id="content"&gt;
     [java] &lt;h1&gt;Package com.liferay.poshi.runner&lt;/h1&gt;
     [java] &lt;div class="breadcrumbs"&gt;
     [java] &lt;a href="../index.html"&gt;all&lt;/a&gt; &amp;gt; com.liferay.poshi.runner&lt;/div&gt;
     [java] &lt;div id="summary"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="summaryGroup"&gt;
     [java] &lt;table&gt;
     [java] &lt;tr&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="tests"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;tests&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="failures"&gt;
     [java] &lt;div class="counter"&gt;1&lt;/div&gt;
     [java] &lt;p&gt;failures&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="ignored"&gt;
     [java] &lt;div class="counter"&gt;0&lt;/div&gt;
     [java] &lt;p&gt;ignored&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox" id="duration"&gt;
     [java] &lt;div class="counter"&gt;56.335s&lt;/div&gt;
     [java] &lt;p&gt;duration&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;td&gt;
     [java] &lt;div class="infoBox failures" id="successRate"&gt;
     [java] &lt;div class="percent"&gt;0%&lt;/div&gt;
     [java] &lt;p&gt;successful&lt;/p&gt;
     [java] &lt;/div&gt;
     [java] &lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] &lt;/table&gt;
     [java] &lt;/div&gt;
     [java] 
     [java] &lt;div id="tabs"&gt;
     [java] &lt;ul class="tabLinks"&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab0"&gt;Failed tests&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;li&gt;
     [java] &lt;a href="#tab1"&gt;Classes&lt;/a&gt;
     [java] &lt;/li&gt;
     [java] &lt;/ul&gt;
     [java] 
     [java] &lt;div class="tab" id="tab0"&gt;
     [java] &lt;h2&gt;Failed tests&lt;/h2&gt;
     [java] &lt;ul class="linkList"&gt;
     [java] &lt;li&gt;</code></pre></details></html>

2021-12-01 19:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1158/">test-portal-source-format#1158</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1158/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586029266">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-12-01[11:54:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/3955/">publish-testray-report#3955</a><br/></div></div>

2021-12-01 21:57 UTC, alanafergs commented
ci:test:sf

2021-12-01 21:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/523/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/523/jenkins-report.html">here</a>.</b></p>

2021-12-01 22:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e0ff2b5a59a058709e3f1197f9c1271bd06fe407">e0ff2b5a59a058709e3f1197f9c1271bd06fe407</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/159ca407ade924dbd2058a97706e986b5c362702">159ca407ade924dbd2058a97706e986b5c362702</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/523/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/523/jenkins-report.html">here</a>.</h5></details></html>

2021-12-01 22:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/523/">test-portal-source-format#523</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/523/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586095557">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-12-01[13:57:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/1779/">publish-testray-report#1779</a><br/></div></div>

2021-12-02 16:58 UTC, lucasperj requested changes

2021-12-02 16:58 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/macros/KaleoFormsNewSubmissions.macro
> +			value1 = "1.0");
Please, pass "value1" as a variable, cause the workflow version value can be changed. Thanks!

2021-12-02 16:58 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/macros/KaleoFormsNewSubmissions.macro
> +		LexiconEntry.gotoEllipsisMenuItem(menuItem = "View");
Create a macro to do this and use directily on the testcase file please

2021-12-02 16:58 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase
> +		LexiconEntry.gotoEllipsisMenuItem(menuItem = "View");
Use the macro created to this

2021-12-02 16:58 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase
> +		LexiconEntry.gotoEllipsisMenuItem(menuItem = "View");
Use the macro created to this

2021-12-02 16:58 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase
> +		LexiconEntry.gotoEllipsisMenuItem(menuItem = "View");
Use the macro created to this

2021-12-02 16:58 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase
> +		LexiconEntry.gotoEllipsisMenuItem(menuItem = "View");
Use the macro created to this

2021-12-02 16:58 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase
> +		LexiconEntry.gotoEllipsisMenuItem(menuItem = "View");
Use the macro created to this

2021-12-02 16:58 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase
> +		KaleoFormsNewSubmissions.viewVersionOnDetails();
Remeber to pass the variable here after you change the macro

2021-12-02 17:44 UTC, alanafergs commented
ci:test:sf

2021-12-02 17:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/1274/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/1274/jenkins-report.html">here</a>.</b></p>

2021-12-02 17:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4d46589e335404a237346a38d2ba933c0867fdfb">4d46589e335404a237346a38d2ba933c0867fdfb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/93a519aafeaffe8488757f2563f7495e3aa5b8b2">93a519aafeaffe8488757f2563f7495e3aa5b8b2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/1274/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/1274/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre><code>     [exec] 1 errors in POSHI
     [exec] 
     [exec] Invalid value1 attribute
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsProcessSubmissionsDetails.testcase:230
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':validatePoshi'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED</code></pre></p></div></details></html>

2021-12-02 17:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/1274/">test-portal-source-format#1274</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/1274/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586551996">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-12-02[09:44:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/4294/">publish-testray-report#4294</a><br/></div></div>

2021-12-02 18:04 UTC, alanafergs commented
ci:test:sf

2021-12-02 18:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/1179/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1179/jenkins-report.html">here</a>.</b></p>

2021-12-02 18:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4d46589e335404a237346a38d2ba933c0867fdfb">4d46589e335404a237346a38d2ba933c0867fdfb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-70703">LRQA-70703</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/4c8c7c77a6d03e96fa88f143c3d8d9a64c8cd89d">4c8c7c77a6d03e96fa88f143c3d8d9a64c8cd89d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1179/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1179/jenkins-report.html">here</a>.</h5></details></html>

2021-12-02 18:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1179/">test-portal-source-format#1179</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1179/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/107">lucasperj#107</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586591209">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#107 - 2021-12-02[10:05:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/4007/">publish-testray-report#4007</a><br/></div></div>

2021-12-02 18:12 UTC, lucasperj approved these changes

2021-12-02 18:12 UTC, lucasperj commented
ci:forward

2021-12-02 18:12 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-12-02 18:12 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-12-02 18:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/forward-pullrequest/36//consoleFull)

2021-12-02 18:13 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/110674
[Console](https://test-1-35.liferay.com/job/forward-pullrequest/36//consoleFull)

2021-12-02 18:13 UTC, closed without merging