LRQA-71598
lucasperj/liferay-portal pull request #163
Opened 2021-12-01 22:59 UTC by andreefarias

2021-12-01 22:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-12-01 23:00 UTC, andreefarias commented
ci:test:sf

2021-12-01 23:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/920/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/920/jenkins-report.html">here</a>.</b></p>

2021-12-01 23:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e0ff2b5a59a058709e3f1197f9c1271bd06fe407">e0ff2b5a59a058709e3f1197f9c1271bd06fe407</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LRQA-71598">LRQA-71598</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/b3e0d1f35c5cc14ba4d51c38d7b4cc1fa85db50b">b3e0d1f35c5cc14ba4d51c38d7b4cc1fa85db50b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/920/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/920/jenkins-report.html">here</a>.</h5></details></html>

2021-12-01 23:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/920/">test-portal-source-format#920</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/920/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/163">lucasperj#163</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586107545">[master] ci:test:sf - andreefarias &gt; lucasperj - PR#163 - 2021-12-01[15:00:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/2944/">publish-testray-report#2944</a><br/></div></div>

2021-12-02 19:01 UTC, lucasperj requested changes

2021-12-02 19:01 UTC, lucasperj commented on modules/apps/calendar/calendar-web-test/src/testFunctional/tests/AddCalendar.testcase
> +		PortalSettings.configureTimeZone(timeZone = "(UTC) Coordinated Universal Time");
Here you can use "(UTC -02:00) Brasilia Summer Time", cause i think (UTC) Coordinated Universal Time) already is the default used. Thanks

2021-12-02 19:01 UTC, lucasperj commented on modules/apps/calendar/calendar-web-test/src/testFunctional/tests/AddCalendar.testcase
> +		Calendar.viewSelectedTimeZone(timeZone = "(UTC) Coordinated Universal Time");
Here you may assert the "(UTC -02:00) Brasilia Summer Time", cause i think (UTC) Coordinated Universal Time) already is the default used. Thanks

2021-12-02 19:45 UTC, andreefarias commented
ci:test:sf

2021-12-02 19:53 UTC, lucasperj approved these changes

2021-12-02 20:27 UTC, lucasperj commented
ci:test:sf

2021-12-02 20:36 UTC, lucasperj commented
ci:test:sf

2021-12-02 20:50 UTC, lucasperj commented
ci:test:sf

2021-12-02 21:00 UTC, lucasperj commented
ci:stop

2021-12-02 21:09 UTC, lucasperj commented
ci:stop

2021-12-02 21:14 UTC, lucasperj commented
ci:forward

2021-12-02 21:14 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-12-02 21:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/985/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/985/jenkins-report.html">here</a>.</b></p>

2021-12-02 21:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/940/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/940/jenkins-report.html">here</a>.</b></p>

2021-12-02 21:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b7534286b84c9791bda8bc619e0d631d07f44379">b7534286b84c9791bda8bc619e0d631d07f44379</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LRQA-71598">LRQA-71598</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/4cd6a935310ac3cb8298d4f22b9881f90ecaf202">4cd6a935310ac3cb8298d4f22b9881f90ecaf202</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/940/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/940/jenkins-report.html">here</a>.</h5></details></html>

2021-12-02 21:18 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/940//consoleFull)

2021-12-02 21:18 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/110688
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/940//consoleFull)

2021-12-02 21:18 UTC, closed without merging

2021-12-02 21:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/985/">test-portal-acceptance-pullrequest(master)#985</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/985/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/163">lucasperj#163</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586691448">[master] ci:test:relevant - andreefarias &gt; lucasperj - PR#163 - 2021-12-02[13:14:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2871/">publish-testray-report#2871</a><br/></div></div>

2021-12-02 21:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/940/">test-portal-source-format#940</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/940/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/163">lucasperj#163</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586691615">[master] ci:test:sf - andreefarias &gt; lucasperj - PR#163 - 2021-12-02[13:14:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/2999/">publish-testray-report#2999</a><br/></div></div>