LRQA-71621
lucasperj/liferay-portal pull request #210
Opened 2021-12-23 14:10 UTC by Italo-gabriel

2021-12-23 14:13 UTC, Italo-gabriel commented
ci:test:sf

2022-01-18 19:34 UTC, Italo-gabriel commented
ci:test:sf

2022-01-18 19:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/4897/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4897/jenkins-report.html">here</a>.</b></p>

2022-01-18 19:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8e6c53e6173b2c9cd061966e585c55f6fffeb3bb">8e6c53e6173b2c9cd061966e585c55f6fffeb3bb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Italo-gabriel/liferay-portal/tree/LRQA-71621">LRQA-71621</a><br/>Branch GIT ID: <a href="https://github.com/Italo-gabriel/liferay-portal/commit/3151f5f45c8b45043c8146831568de11d5a38328">3151f5f45c8b45043c8146831568de11d5a38328</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4897/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4897/jenkins-report.html">here</a>.</h5></details></html>

2022-01-18 19:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4897/">test-portal-source-format#4897</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4897/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/210">lucasperj#210</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1601188680">[master] ci:test:sf - Italo-gabriel &gt; lucasperj - PR#210 - 2022-01-18[11:37:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/2467/">publish-testray-report#2467</a><br/></div></div>

2022-01-31 20:36 UTC, alanafergs commented
Just started reviewing :)

2022-04-04 21:56 UTC, lucasperj requested changes

2022-04-04 21:56 UTC, lucasperj commented on modules/apps/calendar/calendar-web-test/src/testFunctional/tests/CalendarConfiguration.testcase
> +        CalendarConfiguration.viewSelectDefaultDuration(defaultDuration = "15 Minutes");
In this test, you are manually entering the desired time and the time space that we are trying to verify(15, 45, 60 minutes). You can look for a way to insert the event without directly interfering with the time, being able to just check if the default time was modified during the test. 
You can take a look at the macro 
```
CalendarScheduler.addLocalizedEvent(
			eventTitle = "Calendar Event Title",
			saveButton = "Save",
			viewType = "Week");
```

2023-08-08 15:45 UTC, closed without merging