LPS 163243
lucasperj/liferay-portal pull request #318
Opened 2022-12-19 17:28 UTC by sofiamendozalr

- LPS-163243 Add execute-all-pending-upgrades-from-gogo-shell to build-test-db-upgrade-client.xml
- LPS-163243 Add ExecuteAllPendingUpgradesFromGogoShell testcase

2022-12-19 17:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-28 20:36 UTC, susanchen3 requested changes
Can you update your liferay portal? I changed the location of `DatabaseUpgradeClient.testcase` in a recent PR and it doesn't seem to be updated for you. Hopefully this should fix your issues.

This is what it looks like for me locally when I was testing: https://github.com/susanchen3/liferay-portal/pull/105

2022-12-28 20:36 UTC, susanchen3 commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/DatabaseUpgradeClient.testcase
> +	test ExecuteAllPendingUpgradesFromGogoShell {
Add 
```
property skip.get.testcase.database.properties = "true";
property skip.upgrade-legacy-database = "true";
```

2022-12-28 20:36 UTC, susanchen3 commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalDatabaseValidationUpgrade.testcase
> -		property data.archive.type = "data-archive-portal";
Why are we removing this? :thinking:

2022-12-29 09:13 UTC, sofiamendozalr commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalDatabaseValidationUpgrade.testcase
> -		property data.archive.type = "data-archive-portal";
I think I deleted it by mistake :(

2023-01-11 18:07 UTC, lucasperj commented
Hey @sofiamendozalr , can you organize your commits, rebase your branch and also send a commit with the expect file please? Thank you so much! :smile:

2023-01-25 17:02 UTC, sofiamendozalr commented
@vicnate5

2023-01-25 22:31 UTC, vicnate5 commented
See https://github.com/vicnate5/liferay-portal/pull/2244

2023-01-25 22:31 UTC, vicnate5 commented
ci:close

2023-01-25 22:31 UTC, closed without merging