LRQA-82599
lucasperj/liferay-portal pull request #375
Opened 2023-09-05 18:33 UTC by HenriiqueSantos

2023-09-06 15:50 UTC, lucasperj requested changes

2023-09-06 15:50 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +		Navigator.openURL();
Please check : https://github.com/lucasperj/liferay-portal/pull/372/files#r1315969960

2023-09-06 15:50 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +			Form.save();
Please check : https://github.com/lucasperj/liferay-portal/pull/372/files#r1315997906

2023-09-06 15:50 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +
- Please check : https://github.com/lucasperj/liferay-portal/pull/372#issuecomment-1706815755

Finally, what we talked about on Friday, the ideal here would be for you to either edit the existing commit to change the wrong message OR reset it to the upstream hash after the rebase and commit again, but not put the other commit on top with just the changes and practically the same commit message, in the commit history the commit with the wrong message still appears and makes it more confusing when reviewing, please fix that.

2023-09-06 15:50 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +			FormPortlet.submit();
- Use just FormPortlet.submitSuccessfully();, this way you ensure that the form has been submitted

2023-09-06 21:07 UTC, lucasperj commented
@HenriiqueSantos 

- Still need to fix the commit message of [66d77](https://github.com/lucasperj/liferay-portal/pull/375/commits/16de9c0580afb46bd7b0dd2f28e0da1f93e66d77)
- Remember to change the post commit message of [0fa37](https://github.com/lucasperj/liferay-portal/pull/375/commits/d4a303085d288904effb08575cde44d3eff0fa37) only mentioning the changes that were made
- A different and maybe easy solution would be, as suggested earlier, to reset to the upstream hash after rebasing and committing again. Please fix it. Any questions send me a message on slack

2023-09-08 13:57 UTC, HenriiqueSantos commented
ci:test:sf

2023-09-08 14:18 UTC, lucasperj requested changes

2023-09-08 14:18 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +
:yellow_circle: Empty line, as we talked some minutes ago, you need to execute SF after make changes

2023-09-08 14:18 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +
:yellow_circle: Empty line, as we talked some minutes ago, you need to execute SF after make changes

2023-09-08 14:18 UTC, lucasperj commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTests.testcase
> +
:yellow_circle: Empty line, as we talked some minutes ago, you need to execute SF after make changes

2023-09-11 20:56 UTC, lucasperj commented
Looks good to me :rocket:

2023-09-11 20:56 UTC, closed without merging