LRQA-69709 Workflow Automated Test - CanSeeStateBeforeAssign
lucasperj/liferay-portal pull request #66
Opened 2021-10-11 20:58 UTC by alanafergs

https://issues.liferay.com/browse/LRQA-69709

2021-10-11 20:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-10-11 20:58 UTC, alanafergs commented
ci:test:sf

2021-11-01 20:28 UTC, andreefarias requested changes

2021-11-01 20:28 UTC, andreefarias commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase
> +			locator1 = "AssetWorkflow#ASSET_STATE");
Look for a macro for that, maybe Workflow.viewTaskAssignedToMyRoles make this. Thanks!

2021-11-01 20:39 UTC, andreefarias requested changes

2021-11-01 20:39 UTC, andreefarias commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase
>  	@priority = "3"
Change priority to "4". Thanks!

2021-11-01 20:40 UTC, andreefarias requested changes

2021-11-01 20:40 UTC, andreefarias commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase
>  	@priority = "3"
Change priority to "4". Thanks!

2022-08-31 17:35 UTC, closed without merging