LRQA-69711 Workflow Automated Test - CanSeeStateAfterReject
lucasperj/liferay-portal pull request #69
Opened 2021-10-13 19:45 UTC by alanafergs

https://issues.liferay.com/browse/LRQA-69711

2021-10-13 19:51 UTC, alanafergs commented
ci:test:sf

2021-10-13 21:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ffa6f1a8fd2a717d87c53e3dd13e35be5aeada00">ffa6f1a8fd2a717d87c53e3dd13e35be5aeada00</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-69711">LRQA-69711</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/b2656f5cc7b68e866794b2fbc9cc7f53b39928c5">b2656f5cc7b68e866794b2fbc9cc7f53b39928c5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/676/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/676/jenkins-report.html">here</a>.</h5></details></html>

2021-10-13 21:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/676/">test-portal-source-format#676</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/676/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/69">lucasperj#69</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1568754400">[master] ci:test:sf - alanafergs &gt; lucasperj - PR#69 - 2021-10-13[14:38:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/2223/">publish-testray-report#2223</a><br/></div></div>

2021-11-01 21:00 UTC, andreefarias requested changes

2021-11-01 21:00 UTC, andreefarias commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase
> +			value1 = "userfn userln");
Look for a macro for this, if it doesn't exist, create one. Thanks!

2022-08-31 17:35 UTC, closed without merging