LRQA-69712 Workflow Automated Test - CanApproveByNotifications
lucasperj/liferay-portal pull request #71
Opened 2021-10-13 20:59 UTC by alanafergs

https://issues.liferay.com/browse/LRQA-69712

2021-10-14 18:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/41ac354cd0aa3f9d851a37a6a62d8167f81a2bce">41ac354cd0aa3f9d851a37a6a62d8167f81a2bce</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRQA-69712">LRQA-69712</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/b1a7178853483455c5ad32cb700096a3f9a25d69">b1a7178853483455c5ad32cb700096a3f9a25d69</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5765/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5765/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/macros/WorkflowUser.macro expected:&lt;definition \{
     [java] 
     [java] [	macro disableCaptchaToCreateNewUser \{
     [java] 		ApplicationsMenu.gotoPortlet(
     [java] 			category = "Configuration",
     [java] 			panel = "Control Panel",
     [java] 			portlet = "System Settings");
     [java] 
     [java] 		SystemSettings.gotoConfiguration(
     [java] 			configurationCategory = "Security Tools",
     [java] 			configurationName = "CAPTCHA",
     [java] 			configurationScope = "System Scope");
     [java] 
     [java] 		SystemSettings.configureSystemSetting(
     [java] 			enableSetting = "false",
     [java] 			settingFieldName = "Create Account CAPTCHA Enabled");
     [java] 
     [java] 		Refresh();
     [java] 	\}
     [java] 
     [java] \}]&gt; but was:&lt;definition \{
     [java] 
     [java] [    macro disableCaptchaToCreateNewUser\{
     [java]         ApplicationsMenu.gotoPortlet(
     [java] 			category = "Configuration",
     [java] 			panel = "Control Panel",
     [java] 			portlet = "System Settings");
     [java] 
     [java] 		SystemSettings.gotoConfiguration(
     [java] 			configurationCategory = "Security Tools",
     [java] 			configurationName = "CAPTCHA",
     [java] 			configurationScope = "System Scope");
     [java] 
     [java] 		SystemSettings.configureSystemSetting(
     [java] 			enableSetting = "false",
     [java] 			settingFieldName = "Create Account CAPTCHA Enabled");
     [java] 
     [java] 		Refresh();
     [java] 
     [java]     \}
     [java] 
     [java] 
     [java] \} ]&gt;
     [java] 2: ./modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase expected:&lt;... "userfn userln");
     [java] 	[]\}
     [java] 
     [java] 	@description = "...&gt; but was:&lt;... "userfn userln");
     [java] 	[		
     [java] 
     [java] 	]\}
     [java] 
     [java] 	@description = "...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:287)
[stopwatch] [run.batch.test.action: 1:13.931 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:</code></pre></details></html>

2021-10-15 21:26 UTC, alanafergs commented
ci:test:sf

2021-10-15 21:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/309/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com//userContent/jobs/test-portal-source-format/builds/309/jenkins-report.html">here</a>.</b></p>

2021-11-01 21:30 UTC, andreefarias requested changes

2021-11-01 21:30 UTC, andreefarias commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase
> +			value1 = "sent you a User for review in the workflow.");
Look for a macro for this, if it doesn't exist, create one. Thanks!

2021-11-01 21:34 UTC, andreefarias requested changes

2021-11-01 21:34 UTC, andreefarias commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowUser.testcase
> +			value1 = "sent you a User for review in the workflow.");
Look for a macro for this, if it doesn't exist, create one. Thanks!

2022-08-31 17:34 UTC, closed without merging