Combined PR of KaleoFormsNewProcess testcases: LRQA-70678, LRQA-70680, LRQA-70681, LRQA-70682, LRQA-70683, LRQA-70684, LRQA-70685, LRQA-70686
lucasperj/liferay-portal pull request #79
Opened 2021-10-19 18:38 UTC by alessandromalves

https://issues.liferay.com/browse/LRQA-70644

2021-10-19 18:41 UTC, alessandromalves commented
ci:test:sf

2021-11-01 16:37 UTC, lucasperj approved these changes

2021-11-04 20:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/657/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/657/jenkins-report.html">here</a>.</b></p>

2021-11-04 20:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/628dd273eb93deb7a3e8dd0625075012033fca73">628dd273eb93deb7a3e8dd0625075012033fca73</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LRQA-70677">LRQA-70677</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/50656807bc7cb61be6cf29545744fb5afa7f97bf">50656807bc7cb61be6cf29545744fb5afa7f97bf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/657/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/657/jenkins-report.html">here</a>.</h5></details></html>

2021-11-04 20:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/657/">test-portal-source-format#657</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/657/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/79">lucasperj#79</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1576159294">[master] ci:test:sf - alessandromalves &gt; lucasperj - PR#79 - 2021-11-04[13:33:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/2114/">publish-testray-report#2114</a><br/></div></div>

2021-11-08 18:45 UTC, lucasperj requested changes

2021-11-08 18:45 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoFormsNewProcess.testcase
> +		KaleoFormsAdmin.saveProcess(kfProcessName = "Kaleo Forms Process");
You can create a macro to add a workflow. Thank you!

2021-11-08 18:56 UTC, lucasperj commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/macros/KaleoFormsAdmin.macro
> +	}
Very good, this is a very interesting macro Alessandro, congratulations!

2021-11-08 21:39 UTC, lucasperj commented
ci:test:sf

2021-11-08 21:41 UTC, lucasperj approved these changes

2021-11-08 21:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/806/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/806/jenkins-report.html">here</a>.</b></p>

2021-11-08 21:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b6e202c32fb58fca5a54f9b4b5adb21351f67a42">b6e202c32fb58fca5a54f9b4b5adb21351f67a42</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alessandromalves/liferay-portal/tree/LRQA-70677">LRQA-70677</a><br/>Branch GIT ID: <a href="https://github.com/alessandromalves/liferay-portal/commit/1254a2e09b8780cb6ce987cba1f3a5f70e0ddc19">1254a2e09b8780cb6ce987cba1f3a5f70e0ddc19</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/806/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/806/jenkins-report.html">here</a>.</h5></details></html>

2021-11-08 21:46 UTC, lucasperj commented
ci:forward

2021-11-08 21:46 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-11-08 21:46 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-11-08 21:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/806/">test-portal-source-format#806</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/806/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lucasperj/liferay-portal/pull/79">lucasperj#79</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1577498339">[master] ci:test:sf - alessandromalves &gt; lucasperj - PR#79 - 2021-11-08[13:42:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/2729/">publish-testray-report#2729</a><br/></div></div>

2021-11-08 21:47 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-31.liferay.com/job/forward-pullrequest/135//consoleFull)

2021-11-08 21:47 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/109603
[Console](https://test-1-31.liferay.com/job/forward-pullrequest/135//consoleFull)

2021-11-08 21:47 UTC, closed without merging